export const menuCategories = [
  {
    title: "मुख्य व्यंजन (Main Dishes)",
    items: [
      {
        name: "Mithila Dal Bhat",
        description: "Traditional lentil curry with steamed rice, a staple of Mithila cuisine",
        price: "₹180",
        isVeg: true,
        isSpecial: true,
        image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&q=80&w=400&h=300",
        ingredients: ["Basmati Rice", "Mixed Lentils", "Turmeric", "Cumin", "Ginger", "Garlic", "Ghee"],
        preparationTime: "25 minutes",
        spiceLevel: 2,
        calories: "420 kcal",
        allergens: ["Gluten"],
        story:
          "This traditional combination has been the heart of Mithila meals for centuries, representing the perfect balance of protein and carbohydrates.",
      },
      {
        name: "Sattu Paratha",
        description: "Stuffed flatbread with roasted gram flour and spices",
        price: "₹120",
        isVeg: true,
        image: "/sattuparatha.jpg?height=300&width=400",
        ingredients: ["Wheat Flour", "Roasted Gram Flour", "Onions", "Green Chilies", "Coriander", "Mustard Oil"],
        preparationTime: "20 minutes",
        spiceLevel: 3,
        calories: "350 kcal",
        allergens: ["Gluten"],
        story:
          "A nutritious and filling bread that has sustained farmers and workers in the Mithila region for generations.",
      },
      {
        name: "Mithila Fish Curry",
        description: "Fresh fish cooked in traditional Mithila spices and mustard oil",
        price: "₹280",
        isVeg: false,
        isSpecial: true,
        image: "https://images.unsplash.com/photo-1626074353765-517a681e40be?auto=format&fit=crop&q=80&w=400&h=300",
        ingredients: ["Fresh River Fish", "Mustard Oil", "Panch Phoron", "Turmeric", "Red Chilies", "Tomatoes"],
        preparationTime: "30 minutes",
        spiceLevel: 4,
        calories: "320 kcal",
        allergens: ["Fish"],
        story:
          "Prepared with fish from the sacred rivers of Mithila, this curry represents the region's connection to its waterways.",
      },
      {
        name: "Chokha Platter",
        description: "Mashed vegetables (potato, eggplant, tomato) with mustard oil",
        price: "₹150",
        isVeg: true,
        image: "https://images.unsplash.com/photo-1601050633647-8f8f5f3a07b7?auto=format&fit=crop&q=80&w=400&h=300",
        ingredients: [
          "Roasted Potatoes",
          "Roasted Eggplant",
          "Roasted Tomatoes",
          "Mustard Oil",
          "Green Chilies",
          "Onions",
        ],
        preparationTime: "35 minutes",
        spiceLevel: 3,
        calories: "280 kcal",
        allergens: [],
        story:
          "A rustic dish that celebrates the simple flavors of roasted vegetables, enhanced with aromatic mustard oil.",
      },
    ],
  },
  {
    title: "मिठाई (Sweets)",
    items: [
      {
        name: "Thekua",
        description: "Traditional sweet made with wheat flour, jaggery, and ghee",
        price: "₹80",
        isVeg: true,
        isSpecial: true,
        image: "https://images.unsplash.com/photo-1605191667966-9c5626505878?auto=format&fit=crop&q=80&w=400&h=300",
        ingredients: ["Wheat Flour", "Jaggery", "Ghee", "Coconut", "Fennel Seeds", "Cardamom"],
        preparationTime: "45 minutes",
        spiceLevel: 0,
        calories: "180 kcal",
        allergens: ["Gluten", "Dairy"],
        story: "A sacred sweet offered during Chhath Puja, symbolizing devotion and tradition in Mithila culture.",
      },
      {
        name: "Malpua",
        description: "Sweet pancakes soaked in sugar syrup, served hot",
        price: "₹100",
        isVeg: true,
        image: "https://images.unsplash.com/photo-1589119908995-c6837fa14848?auto=format&fit=crop&q=80&w=400&h=300",
        ingredients: ["All-purpose Flour", "Milk", "Sugar", "Cardamom", "Ghee", "Pistachios"],
        preparationTime: "25 minutes",
        spiceLevel: 0,
        calories: "250 kcal",
        allergens: ["Gluten", "Dairy", "Nuts"],
        story:
          "These golden, syrup-soaked pancakes are a festival favorite, bringing sweetness to every celebration.",
      },
      {
        name: "Kheer",
        description: "Creamy rice pudding with cardamom and nuts",
        price: "₹90",
        isVeg: true,
        image: "https://images.unsplash.com/photo-1596450514735-373e34346890?auto=format&fit=crop&q=80&w=400&h=300",
        ingredients: ["Basmati Rice", "Full-fat Milk", "Sugar", "Cardamom", "Almonds", "Pistachios", "Saffron"],
        preparationTime: "40 minutes",
        spiceLevel: 0,
        calories: "220 kcal",
        allergens: ["Dairy", "Nuts"],
        story: "A creamy delight that graces every auspicious occasion, representing prosperity and joy.",
      },
    ],
  },
  {
    title: "पेय (Beverages)",
    items: [
      {
        name: "Lassi",
        description: "Traditional yogurt-based drink, sweet or salted",
        price: "₹60",
        isVeg: true,
        image: "https://images.unsplash.com/photo-1571006682864-740429de3073?auto=format&fit=crop&q=80&w=400&h=300",
        ingredients: ["Fresh Yogurt", "Sugar/Salt", "Cardamom", "Rose Water", "Mint"],
        preparationTime: "5 minutes",
        spiceLevel: 0,
        calories: "150 kcal",
        allergens: ["Dairy"],
        story: "A cooling beverage that provides relief from the heat while aiding digestion after hearty meals.",
      },
      {
        name: "Sattu Drink",
        description: "Refreshing drink made with roasted gram flour",
        price: "₹50",
        isVeg: true,
        image: "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&q=80&w=400&h=300",
        ingredients: ["Roasted Gram Flour", "Water", "Salt", "Lemon", "Mint", "Black Salt"],
        preparationTime: "3 minutes",
        spiceLevel: 1,
        calories: "120 kcal",
        allergens: [],
        story: "A nutritious and energizing drink that has been the go-to refreshment for laborers and travelers.",
      },
      {
        name: "Masala Chai",
        description: "Spiced tea brewed with traditional Mithila spices",
        price: "₹30",
        isVeg: true,
        image: "https://images.unsplash.com/photo-1544787210-282713df01ef?auto=format&fit=crop&q=80&w=400&h=300",
        ingredients: ["Black Tea", "Milk", "Cardamom", "Cinnamon", "Ginger", "Cloves", "Sugar"],
        preparationTime: "8 minutes",
        spiceLevel: 2,
        calories: "80 kcal",
        allergens: ["Dairy"],
        story: "The perfect blend of spices that awakens the senses and brings people together for conversations.",
      },
    ],
  },
];

export const galleryImages = [
  {
    src: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&q=80&w=600&h=400",
    alt: "Traditional Mithila Dal Bhat",
    title: "Dal Bhat Thali",
  },
  {
    src: "/sattuparatha.jpg",
    alt: "Fresh Sattu Paratha",
    title: "Sattu Paratha",
  },
  {
    src: "https://images.unsplash.com/photo-1626074353765-517a681e40be?auto=format&fit=crop&q=80&w=600&h=400",
    alt: "Mithila Fish Curry",
    title: "Fish Curry",
  },
  {
    src: "https://images.unsplash.com/photo-1605191667966-9c5626505878?auto=format&fit=crop&q=80&w=600&h=400",
    alt: "Traditional Thekua",
    title: "Thekua Sweets",
  },
  {
    src: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&q=80&w=600&h=400",
    alt: "Restaurant Interior",
    title: "Our Restaurant",
  },
  {
    src: "https://images.unsplash.com/photo-1582281227059-741ab997a513?auto=format&fit=crop&q=80&w=600&h=400",
    alt: "Mithila Art Decoration",
    title: "Traditional Decor",
  },
];
